services:
  traefik:
    container_name: ${PROJECT_NAME}_traefik
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    # para que funcione la soluci√≥n *.localhost
    # network_mode: "host"
    ports:
      - "${TRAEFIK_HOST_PORT}:${TRAEFIK_SERVICE_CONTAINER_PORT}"
    networks:
      - binaural
  db:
    image: postgres:${POSTGRES_IMG_VERSION}
    container_name: ${PROJECT_NAME}_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data/pgdata
    networks:
      - binaural
  pgadmin:
    container_name: ${PROJECT_NAME}_pgadmin_container
    image: dpage/pgadmin4
    ports:
      - "${PG_ADMIN_HOST_PORT}:${PG_ADMIN_SERVICE_CONTAINER_PORT}"
    environment:
      PGADMIN_DEFAULT_EMAIL: binaural.ca@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoo
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - odoo-pgadmin:/root/.pgadmin
    networks:
      - binaural
  dns:
    image: cytopia/bind:alpine-0.30
    environment:
      DNS_A: "*.odoo.localhost=172.20.${ODOO_MINOR}.1"
      DNS_FORWARDER: 127.0.0.11
    networks:
      binaural:
        ipv4_address: 172.20.${ODOO_MINOR}.10
  odoo:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: ./.resources/Dockerfile
    ports:
      - "${PORT_SERVICE_HOST_ODOO}:${PORT_SERVICE_CONTAINER_ODOO}"
    depends_on:
      - db
      - dns
      - traefik
    volumes:
      - odoo-web:/var/lib/odoo
      - ./src:/home/odoo/src
      - odoo_data:/home/odoo/data
      - py3:/usr/local/lib/
      - py:/usr/lib/
    command: odoo --dev=all
    labels:
      - traefik.enable=true
      - traefik.frontend.port=8069
      - traefik.frontend.rule=HostRegexp:$DOMAIN,{subdomain:[a-z0-9-_]+}.$DOMAIN
      # - traefik.frontend.priority=10
      # - traefik.longpolling.port=8072
      # - traefik.longpolling.frontend.rule=HostRegexp:$DOMAIN,{subdomain:[a-z0-9-_]+}.$DOMAIN;PathPrefix:/longpolling/
      - traefik.backend.loadbalancer.stickiness=true
      - traefik.backend.loadbalancer.method=drr
      # traefik.frontend.redirect.regex: $strTraefikRedirectRegex
      # traefik.frontend.redirect.replacement: $strTraefikRedirectReplacement
    environment:
      CUSTOM_CONFIG: |-
        [options]
      CUSTOM_REQUIREMTNS: |-
        # custom pip librearies
      CUSTOM_ENTRYPOINT: |-
        #!/bin/bash
        # pip install --user --no-cache-dir -e /home/odoo/custom/odoo
        # pip install --user --no-cache-dir pyopenssl
      SMTP_SERVER: mailhog
      SMTP_PORT: 1025
      DBFILTER: ${DBFILTER}
      SERVER_WIDE_MODULES: ${SERVER_WIDE_MODULES}
      MAX_CRON_THREADS: ${MAX_CRON_THREADS}
      WORKERS: ${WORKERS}
      LIST_DB: ${LIST_DB}
      WITHOUT_DEMO: ${WITHOUT_DEMO}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PROXY_MODE: ${PROXY_MODE}
      SERVER_MODE: ${SERVER_MODE}
      AEROO_DOCS_HOST: ${AEROO_DOCS_HOST}
      LIMIT_TIME_REAL_CRON: ${LIMIT_TIME_REAL_CRON}
      LIMIT_TIME_REAL: ${LIMIT_TIME_REAL}
      UNACCENT: ${UNACCENT}
      LOG_LEVEL: info
    dns:
      - 172.20.${ODOO_MINOR}.10
    networks:
      binaural:

volumes:
  odoo-web:
  odoo-db:
  odoo_data:
  py3:
  py:
  odoo-pgadmin:

networks:
  binaural:
    driver: bridge
    external: false
    name: odoo-${ODOO_VERSION}
    ipam:
      config:
        - subnet: 172.20.${ODOO_MINOR}.0/24
